spring.application.name=ridego

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=86400000

server.port=9091

spring.data.mongodb.database=ridego
spring.data.mongodb.uri=mongodb://localhost:27017/ridego

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG